stages:
  - test
  - deploy

pages:
  stage: deploy
  script:
    - rm -rf public
    - mkdir public
    - doxygen commlib.conf
    - cp -r doc/html/* public
  artifacts:
    paths:
    - public
  only:
    - master  
  tags:
    - juelich,centos

centos_docker:
  stage: test
  image: bolnykh/images:ubuntu-gcc-7.1-mpich
  script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DINCLUDE_TESTS=YES -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DDOWNLOAD_GTEST=NO ..
    - make -j 4
    - ctest --output-on-failure
  tags:
    - docker

centos_coverage:
  stage: test
  script:
    - module load gcc/6.3.0 ompi/2.1.0/gcc-6.3.0 cmake/3.7.2 gtest/gcc-6.3.0
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DINCLUDE_TESTS=YES -DCODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug -DDOWNLOAD_GTEST=NO ..
    - make -j 4
    - ctest --output-on-failure
    - ctest -D ExperimentalCoverage
  tags:
    - juelich,centos

centos_intel:
  stage: test
  script:
    - module load cmake/3.7.2 intel/2017 mpich/3.2/intel_17 gtest/intel-17
    - mkdir build
    - cd build
    - cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DINCLUDE_TESTS=YES -DCMAKE_BUILD_TYPE=Debug -DDOWNLOAD_GTEST=NO ..
    - make -j 4
    - ctest --output-on-failure
  tags:
    - juelich,centos

#ubuntu_job_gfortran:
#  script:
#    - source ~/prepare_build_gcc.sh
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DINCLUDE_TESTS=YES ..
#    - make -j 4
#    - ctest --output-on-failure
#  tags:
#    - ubuntu
#
#ubuntu_job_intel:
#  script:
#    - source ~/prepare_build_intel.sh
#    - mkdir build
#    - cd build
#    - cmake -DCMAKE_C_COMPILER=icc -DCMAKE_CXX_COMPILER=icpc -DINCLUDE_TESTS=YES ..
#    - make -j 4
#    - ctest --output-on-failure
#  tags:
#    - ubuntu
