before_script:
  - source ~/prepare_build.sh

grsjuc_job:
  script:
    - cmake . -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DINCLUDE_TESTS=ON
    - make
    - make test
  tags:
    - grsjuc,comm_lib

ubuntu_job:
  script:
    - cmake . -DCMAKE_C_COMPILER=mpicc -DCMAKE_CXX_COMPILER=mpicxx -DINCLUDE_TESTS=ON
    - make
    - make test
  tags:
    - ubuntu,comm_lib
